name: awful-falafel
volumes:
  certbot-certs:
    external: true
networks:
  awful-falafel:
    driver: bridge
services:
  web:
    hostname: awful-falafel-web
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - awful-falafel
    volumes:
      - ./config:/rails/config:ro
  nginx:
    image: nginx-more
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx-more
      args:
        ENABLED_MODULES: "headers-more"
    volumes:
      - certbot-certs:/etc/letsencrypt/:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "4433:4433"
    networks:
      - awful-falafel
