# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |"genre_name|"
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

Venue.create([
	{ name: "1894 Taphouse & Spirits", city: "Elmira Heights", state: "NY" },
	{ name: "Brick House Brewery", city: "Corning", state: "NY" },
	{ name: "Butcher's Son", city: "Corning", state: "NY" },
	{ name: "Carey's Brewhouse", city: "Corning", state: "NY" },
	{ name: "Champions Sports Grille", city: "Elmira", state: "NY" },
	{ name: "Corning's Gaffer District", city: "Corning", state: "NY" },
	{ name: "Crooked Creek Campground", city: "Gaines", state: "PA" },
	{ name: "Cugini Cafe", city: "Corning", state: "NY" },
	{ name: "Diversion Brewing Company", city: "Chemung", state: "NY" },
	{ name: "Elkland Moose Lodge #746", city: "Elkland", state: "PA" },
	{ name: "ILL EAGLE Taphouse", city: "Elmira", state: "NY" },
	{ name: "Iron Flamingo Brewery", city: "Corning", state: "NY" },
	{ name: "Krookid Leyk Distilling", city: "Hammondsport", state: "NY" },
	{ name: "Liquid Shoes Brewing", city: "Corning", state: "NY" },
	{ name: "Patrick's Pub", city: "Elmira", state: "NY" },
	{ name: "Private Party" },
	{ name: "Riverfront Park", city: "Sayre", state: "PA" },
	{ name: "Scale House Brewery", city: "Hector", state: "NY" },
	{ name: "Tanner's Bar & Grill", city: "Athens", state: "PA" },
	{ name: "The Office on Market Street", city: "Corning", state: "NY" },
	{ name: "The Roost", city: "Wellsboro", state: "PA" },
	{ name: "TripEnd Brewing", city: "Troupsburg", state: "NY" },
	{ name: "Upstate Brewing Company", city: "Elmira", state: "NY" },
	{ name: "VOLO", city: "Corning", state: "NY" },
	{ name: "Valley Arts4All", city: "Sayre", state: "PA" },
	{ name: "Watkins Glen International", city: "Watkins Glen", state: "NY" },
	{ name: "Wellsboro Fireman's Annex", city: "Wellsboro", state: "PA" }
])

show_list = {
	"1894 Taphouse & Spirits":	[{ "date": "2024-04-19T04:00:00.000Z", "name": nil, "social_link": "https://www.facebook.com/events/2472204516297774" }, { "date": "2024-07-11T04:00:00.000Z ", "name": "Awful Falafel @1894 Taphouse", "social_link": "https://www.facebook.com/events/1536407406917849/" }],
	"Brick House Brewery":	[{ "date": "2019-04-13T04:00:00.000Z", "name": "Awful Falafel at Brick House Brewery", "social_link": "https://www.facebook.com/events/324518721586677/" }],
	"Butcher's Son":	[{ "date": "2023-09-16T04:00:00.000Z", "name": nil, "social_link": "https://www.facebook.com/events/306565938725821/" }],
	"Carey's Brewhouse":	[{ "date": "2024-03-23T04:00:00.000Z", "name": nil, "social_link": "https://www.facebook.com/events/345781431681678" }],
	"Champions Sports Grille":	[{ "date": "2024-03-02T05:00:00.000Z", "name": nil, "social_link": "https://www.facebook.com/events/742735237782604" }],
	"Corning's Gaffer District":	[{ "date": "2023-02-17T05:00:00.000Z", "name": "CHILL", "social_link": "https://www.facebook.com/events/705491634507225/" }],
	"Crooked Creek Campground":	[{ "date": "2023-07-21T04:00:00.000Z", "name": "Houston Baker and Awful Falafel at Wilderfest", "social_link": "https://www.facebook.com/events/816013013199973/" }],
	"Cugini Cafe":	[{ "date": "2023-06-29T04:00:00.000Z", "name": "Awful Falafel at Cugini Cafe", "social_link": "https://www.facebook.com/events/1684892045293274/" }, { "date": "2019-11-02T04:00:00.000Z", "name": "Book Signing", "social_link": "https://www.facebook.com/events/932470313793468/" }, { "date": "2019-02-28T05:00:00.000Z", "name": "Ladies Night Wine Tasting & Live Music", "social_link": "https://www.facebook.com/events/579808669201537/" }],
	"Diversion Brewing Company":	[{ "date": "2019-10-26T04:00:00.000Z", "name": "Awful Falafel at Diversion Brewing Co.", "social_link": "https://www.facebook.com/events/445500862670887/" }, { "date": "2025-06-26 04:00:00", "name": "Awful Falafel @ Diversion Brewing Company", "social_link": "https://www.facebook.com/events/647388324581511/" }],
	"Elkland Moose Lodge #746":	[{ "date": "2019-12-21T05:00:00.000Z", "name": "Burden My Surrender and Awful Falafel at Elkland Moose Lodge #746", "social_link": "https://www.facebook.com/events/952948551758791/" }],
	"ILL EAGLE Taphouse":	[{ "date": "2024-11-07T04:00:00.000Z ", "name": "Awful Falafel @ Ill Eagle Taphouse", "social_link": "https://www.facebook.com/events/2164939277220992/" }],
	"Iron Flamingo Brewery":	[{ "date": "2023-07-14T04:00:00.000Z", "name": "Awful Falafel and Houston Baker at Iron Flamingo @ Baker St", "social_link": "https://www.facebook.com/events/951088692671824/" }, { "date": "2019-08-30T04:00:00.000Z", "name": "Awful Falafel at Iron Flamingo", "social_link": "https://www.facebook.com/events/380200129292343/" }],
	"Krookid Leyk Distilling":	[{ "date": "2024-08-17T04:00:00.000Z", "name": nil, "social_link": "https://www.facebook.com/events/1377564459622915" }, { "date": "2023-09-03T04:00:00.000Z", "name": "Awful Falafel at Krookid Leyk Distilling", "social_link": "https://www.facebook.com/events/972749017094795/" }, { "date": "2023-07-29T04:00:00.000Z", "name": "Houston Baker and Awful Falafel at Krookid Leyk", "social_link": "https://www.facebook.com/events/831236474572000/" }, { "date": "2025-07-26T04:00:00.000Z", "name": "Awful Falafel @ Krookid Leyk Distilling", "social_link": "https://www.facebook.com/events/1354913652416530/" }],
	"Liquid Shoes Brewing":	[{ "date": "2023-10-27T04:00:00.000Z", "name": nil, "social_link": "https://www.facebook.com/events/1080065982980163" }, { "date": "2022-06-04T04:00:00.000Z", "name": "Awful Falafel @ Liquid Shoes", "social_link": "https://www.facebook.com/events/1142582553233816/" }, { "date": "2021-08-07T04:00:00.000Z", "name": "An Evening with Awful Falafel", "social_link": "https://www.facebook.com/events/360458932350816/" }, { "date": "2020-03-14T04:00:00.000Z", "name": "An Evening with Awful Falafel", "social_link": "https://www.facebook.com/events/210554123418335/" }, { "date": "2020-01-18T05:00:00.000Z", "name": "Awful Falafel at Liquid Shoes", "social_link": "https://www.facebook.com/events/978115862553754/" }, { "date": "2019-09-14T04:00:00.000Z", "name": "Awful Falafel at Liquid Shoes (SURPRISE!)", "social_link": "https://www.facebook.com/events/2331609260501249/" }, { "date": "2019-08-17T04:00:00.000Z", "name": "Awful Falafel at Liquid Shoes", "social_link": "https://www.facebook.com/events/871483939885432/" }, { "date": "2019-06-08T04:00:00.000Z", "name": "Awful Falafel at Liquid Shoes!", "social_link": "https://www.facebook.com/events/443098973155767/" }, { "date": "2025-06-07T04:00:00.000Z ", "name": "Awful Falafel @ Liquid Shoes Brewing", "social_link": "https://www.facebook.com/events/3419706494837807/" }, { "date": "2024-06-21T04:00:00.000Z ", "name": "Awful Falafel @ Liquid Shoes", "social_link": "https://www.facebook.com/events/1505551633507683/" }],
	"Patrick's Pub":	[{ "date": "2022-04-30T04:00:00.000Z", "name": "The Rooster! The Sweats! Awful Falafel! Christian Matthew!", "social_link": "https://www.facebook.com/events/446603280602595/" }, { "date": "2020-02-29T05:00:00.000Z", "name": "Awful Falafel at Patrick's", "social_link": "https://www.facebook.com/events/863164800767404/" }, { "date": "2025-06-28T04:00:00.000Z", "name": "Awful Falafel @ Patrick's Pub", "social_link": "https://www.facebook.com/events/1153745483194081/" }, { "date": "2024-08-09T04:00:00.000Z ", "name": "Awful Falafel @ Patrick's", "social_link": "https://www.facebook.com/events/853162792922662/" }],
	"Private Party":	[{ "date": "2024-03-16T04:00:00.000Z", "name": nil, "social_link": nil }, { "date": "2023-10-14T04:00:00.000Z", "name": nil, "social_link": nil }],
	"Riverfront Park":	[{ "date": "2022-05-07T04:00:00.000Z", "name": "Awful Falafel @ Arts4All", "social_link": "https://www.facebook.com/events/1345977325867013/" }, { "date": "2025-05-03T04:00:00.000Z", "name": "Awful Falafel @Arts4All", "social_link": "https://www.facebook.com/events/1321405005636584/" }],
	"Scale House Brewery":	[{ "date": "2023-07-22T04:00:00.000Z", "name": "Houston Baker and Awful Falafel at Scale House", "social_link": "https://www.facebook.com/events/1353271905228002/" }, { "date": "2024-07-07T04:00:00.000Z ", "name": "Baked Falafel @ Scale House Brewery", "social_link": "https://www.facebook.com/events/25997672176545682/" }],
	"Tanner's Bar & Grill":	[{ "date": "2018-11-24T05:00:00.000Z", "name": "SURPLUS+ Live at Tanner’s featuring Awful Falafel!", "social_link": "https://www.facebook.com/events/469811333524827/" }],
	"The Office on Market Street":	[{ "date": "2023-12-16T05:00:00.000Z", "name": nil, "social_link": "https://www.facebook.com/events/318303304046165" }, { "date": "2023-05-25T04:00:00.000Z", "name": "Baked Falafel at The Office", "social_link": "https://www.facebook.com/events/595540062554337/" }, { "date": "2023-02-18T05:00:00.000Z", "name": "Baked Falafel @ The Office!", "social_link": "https://www.facebook.com/events/489399736736374/" }, { "date": "2022-11-11T05:00:00.000Z", "name": "Baked Falafel @ The Office!", "social_link": "https://www.facebook.com/events/635593248041750/" }, { "date": "2022-09-10T04:00:00.000Z", "name": "Awful Falafel & Mike Cavalier at The Office", "social_link": "https://www.facebook.com/events/1292444648192578/" }, { "date": "2022-05-14T04:00:00.000Z", "name": "Baked Falafel @ The Office", "social_link": "https://www.facebook.com/events/951382362314782/" }, { "date": "2022-03-05T05:00:00.000Z", "name": "Awful Falafel & Houston Baker @ The Office!", "social_link": "https://www.facebook.com/events/1009013016376568/" }, { "date": "2021-05-29T04:00:00.000Z", "name": "Awful Falafel at The Office!", "social_link": "https://www.facebook.com/events/1006071519796871/" }, { "date": "2020-02-15T05:00:00.000Z", "name": "Awful Falafel at The Office", "social_link": "https://www.facebook.com/events/545085789427746/" }],
	"The Roost":	[{ "date": "2020-01-03T05:00:00.000Z", "name": "Awful Falafel at The Roost", "social_link": "https://www.facebook.com/events/530049967836367/" }],
	"TripEnd Brewing":	[{ "date": "2019-10-05T04:00:00.000Z", "name": "Awful Falafel at TripEnd Brewing", "social_link": "https://www.facebook.com/events/2819930261372787/" }, { "date": "2018-10-06T04:00:00.000Z", "name": "Awful Falafel at TripEnd Brewing!", "social_link": "https://www.facebook.com/events/292433604921181/" }],
	"Upstate Brewing Company":	[{ "date": "2024-06-25T04:00:00.000Z", "name": nil, "social_link": "https://www.facebook.com/events/403733695792866" }, { "date": "2025-06-03T04:00:00.000Z ", "name": "Awful Falafel @ Upstate Brewing", "social_link": "https://www.facebook.com/events/24305255062398115/" }],
	"VOLO":	[{ "date": "2018-12-07T05:00:00.000Z", "name": "Awful Falafel at VOLO", "social_link": "https://www.facebook.com/events/177085146549638/" }],
	"Valley Arts4All":	[{ "date": "2024-05-05T04:00:00.000Z", "name": nil, "social_link": "https://www.facebook.com/events/391519127031264" }],
	"Watkins Glen International":	[{ "date": "2023-07-09T04:00:00.000Z", "name": "Houston Baker and Awful Falafel at Winefest", "social_link": "https://www.facebook.com/events/213404701617992/" }, { "date": "2024-07-28T04:00:00.000Z ", "name": "Baked Falafel @ Winefest", "social_link": "https://www.facebook.com/events/1129331651482878/" }],
	"Wellsboro Fireman's Annex":	[{ "date": "2019-10-27T04:00:00.000Z", "name": "Gingerstock: The Dennis Gee Jr. Memorial Show", "social_link": "https://www.facebook.com/events/414032362640184/" }]
}

show_list.each do |venue_name, schedule_entries|
	venue = Venue.find_by(name: venue_name)
	venue.schedule_entries.create(schedule_entries)
end

song_list = {
	"4 Non Blondes":	[{ "title": "What's Up" }],
	"A Day To Remember":	[{ "title": "If It Means A Lot To You" }],
	"A-Ha":	[{ "title": "Take On Me" }],
	"ABBA":	[{ "title": "Mamma Mia" }],
	"Adele":	[{ "title": "Hello" }],
	"Alanis Morissette":	[{ "title": "Hand In My Pocket" }, { "title": "Head Over Feet" }, { "title": "Uninvited" }, { "title": "You Learn" }, { "title": "You Oughta Know" }],
	"Alannah Myles":	[{ "title": "Black Velvet" }],
	"Alison Krauss":	[{ "title": "When You Say Nothing At All" }],
	"All-American Rejects":	[{ "title": "Swing Swing" }],
	"America":	[{ "title": "Sister Golden Hair" }],
	"Anberlin":	[{ "title": "Feel Good Drag" }],
	"Ariana Grande":	[{ "title": "Side To Side" }],
	"Audioslave":	[{ "title": "Be Yourself" }],
	"Avril Lavigne":	[{ "title": "Complicated" }],
	"Backstreet Boys":	[{ "title": "As Long As You Love Me" }, { "title": "I Want It That Way" }, { "title": "Quit Playing Games With My Heart" }, { "title": "Show Me The Meaning Of Being Lonely" }],
	"Bad Religion":	[{ "title": "Sorrow" }],
	"Barenaked Ladies":	[{ "title": "Call And Answer" }, { "title": "It's All Been Done" }, { "title": "Jane" }, { "title": "What A Good Boy" }],
	"Bastille":	[{ "title": "Pompeii" }],
	"Beach Boys":	[{ "title": "Don't Worry Baby" }],
	"Ben Folds":	[{ "title": "Not The Same" }],
	"Billy Idol":	[{ "title": "Dancing With Myself" }],
	"Blue Swede":	[{ "title": "Hooked On A Feeling" }],
	"Blues Traveler":	[{ "title": "Run Around" }],
	"Bob Marley":	[{ "title": "Redemption Song" }, { "title": "Stir It Up" }],
	"Bonnie Raitt":	[{ "title": "Have A Heart" }, { "title": "Something To Talk About" }],
	"Brooks & Dunn":	[{ "title": "Boot Scootin' Boogie" }, { "title": "Neon Moon" }],
	"Bruce Cockburn":	[{ "title": "Lovers In A Dangerous Time" }],
	"Bruce Springsteen":	[{ "title": "I'm On Fire" }],
	"Bruno Mars":	[{ "title": "Locked Out Of Heaven" }],
	"Bryan Adams":	[{ "title": "Summer Of 69" }],
	"CHVRCHES":	[{ "title": "Get Out" }],
	"Cher":	[{ "title": "If I Could Turn Back Time" }],
	"Chicago":	[{ "title": "You're The Inspiration" }],
	"Chris Stapleton":	[{ "title": "Tennessee Whiskey" }],
	"Christopher Cross":	[{ "title": "Arthur's Theme (Best That You Can Do)" }],
	"Circa Survive":	[{ "title": "Frozen Creek" }],
	"Coldplay":	[{ "title": "The Scientist" }],
	"Creedence Clearwater Revival":	[{ "title": "Bad Moon Rising" }, { "title": "Have You Ever Seen The Rain" }, { "title": "Lookin' Out My Back Door" }, { "title": "Proud Mary" }],
	"David Shaffer":	[{ "title": "Cloud" }, { "title": "Soon My Love" }],
	"Deana Carter":	[{ "title": "Strawberry Wine" }],
	"Deep Blue Something":	[{ "title": "Breakfast At Tiffany's" }],
	"Del McCoury Band":	[{ "title": "That Old Train" }],
	"Dexy's Midnight Runners":	[{ "title": "Come On Eileen" }],
	"Dishwalla":	[{ "title": "Counting Blue Cars" }],
	"Dolly Parton":	[{ "title": "9 To 5" }],
	"Dolly Parton & Kenny Rogers":	[{ "title": "Islands In The Stream" }],
	"Don Henley":	[{ "title": "Boys Of Summer" }],
	"Dusty Springfield":	[{ "title": "Son Of A Preacher Man" }],
	"Eagles":	[{ "title": "Desperado" }, { "title": "Hotel California" }, { "title": "Take It Easy" }],
	"Echosmith":	[{ "title": "Bright" }],
	"Eddie Money":	[{ "title": "Baby Hold On" }, { "title": "Take Me Home Tonight" }],
	"Edwin McCain":	[{ "title": "I'll Be" }],
	"Elle King":	[{ "title": "Exes And Ohs" }],
	"Elton John":	[{ "title": "Crocodile Rock" }, { "title": "I'm Still Standing" }],
	"Eric Clapton":	[{ "title": "Wonderful Tonight" }],
	"Extreme":	[{ "title": "More Than Words" }],
	"Fastball":	[{ "title": "Out Of My Head" }, { "title": "The Way" }],
	"Fleet Foxes":	[{ "title": "Mykonos" }],
	"Fleetwood Mac":	[{ "title": "Bleed To Love Her" }, { "title": "Dreams" }, { "title": "Go Your Own Way" }, { "title": "Little Lies" }, { "title": "Rhiannon" }],
	"Foo Fighters":	[{ "title": "The Glass" }],
	"Fountains Of Wayne":	[{ "title": "Stacy's Mom" }],
	"Frank Sinatra":	[{ "title": "The Way You Look Tonight" }],
	"Garth Brooks":	[{ "title": "Friends In Low Places" }],
	"George Michael":	[{ "title": "Faith" }],
	"Gin Blossoms":	[{ "title": "29" }, { "title": "Follow You Down" }, { "title": "Hey Jealousy" }, { "title": "Til I Hear It From You" }],
	"Go West":	[{ "title": "King Of Wishful Thinking" }],
	"Goo Goo Dolls":	[{ "title": "Name" }],
	"Gotye":	[{ "title": "Somebody That I Used To Know" }],
	"Huey Lewis":	[{ "title": "Cruisin'" }],
	"Incubus":	[{ "title": "Drive" }, { "title": "Love Hurts" }, { "title": "Talk Shows On Mute" }],
	"Ingrid Michaelson":	[{ "title": "Everybody" }, { "title": "The Way I Am" }],
	"Israel Kamakawiwo'ole":	[{ "title": "Somewhere Over The Rainbow" }],
	"Jackson Browne":	[{ "title": "Doctor My Eyes" }],
	"James Taylor":	[{ "title": "Carolina In My Mind" }, { "title": "Sweet Baby James" }],
	"Jason Derulo":	[{ "title": "Want To Want Me" }],
	"Jet":	[{ "title": "Are You Gonna Be My Girl" }],
	"Jimmy Eat World":	[{ "title": "Authority Song" }, { "title": "Work" }],
	"John Denver":	[{ "title": "Take Me Home, Country Roads" }],
	"John Prine":	[{ "title": "In Spite Of Ourselves" }],
	"Johnny Cash":	[{ "title": "Folsom Prison Blues" }, { "title": "Sunday Morning Coming Down" }],
	"Jonathan Coulton":	[{ "title": "Still Alive" }],
	"Journey":	[{ "title": "Separate Ways" }],
	"Juice Newton":	[{ "title": "Angel Of The Morning" }],
	"Justin Bieber":	[{ "title": "Love Yourself" }],
	"Katrina and the Waves":	[{ "title": "Walking On Sunshine" }],
	"Lady Gaga":	[{ "title": "Telephone" }],
	"Larkin Poe":	[{ "title": "Georgia Off My Mind" }],
	"Led Zeppelin":	[{ "title": "Rock And Roll" }],
	"Lee Ann Womack":	[{ "title": "I Hope You Dance" }],
	"Leona Lewis":	[{ "title": "Bleeding Love" }],
	"Letters to Cleo":	[{ "title": "Cruel To Be Kind" }, { "title": "I Want You To Want Me" }],
	"Lil Nas X":	[{ "title": "Old Town Road" }],
	"Lindsey Buckingham":	[{ "title": "Holiday Road" }],
	"Little Big Town":	[{ "title": "Girl Crush" }],
	"Lorde":	[{ "title": "Royals" }],
	"Madonna":	[{ "title": "Papa Don't Preach" }],
	"Maren Morris":	[{ "title": "Bones" }],
	"Marvin Gaye":	[{ "title": "I Heard It Through The Grapevine" }],
	"Matchbox Twenty":	[{ "title": "Push" }],
	"Melissa Etheridge":	[{ "title": "Come To My Window" }, { "title": "I'm The Only One" }],
	"Meredith Brooks":	[{ "title": "Bitch" }],
	"Metric":	[{ "title": "Breathing Underwater" }, { "title": "Clone" }],
	"Michale Graves":	[{ "title": "Crying On A Saturday Night" }],
	"Miley Cyrus":	[{ "title": "Party In The U.S.A." }, { "title": "See You Again" }, { "title": "Wrecking Ball" }],
	"Mr. Big":	[{ "title": "To Be With You" }],
	"MxPx":	[{ "title": "Responsibility" }],
	"NSYNC":	[{ "title": "Tearing Up My Heart" }],
	"Nanci Griffith":	[{ "title": "Going Back To Georgia" }],
	"Nat King Cole":	[{ "title": "L-O-V-E" }, { "title": "Route 66" }],
	"Natalie Imbruglia":	[{ "title": "Torn" }],
	"Nathaniel Rateliff":	[{ "title": "S.O.B." }],
	"Neil Diamond":	[{ "title": "Sweet Caroline" }],
	"New Multitudes":	[{ "title": "My Revolutionary Mind" }],
	"Nitty Gritty Dirt Band":	[{ "title": "Fishin' In The Dark" }],
	"No Doubt":	[{ "title": "Don't Speak" }, { "title": "Spiderwebs" }],
	"Oasis":	[{ "title": "Champagne Supernova" }, { "title": "Wonderwall" }],
	"Old Crow Medicine Show":	[{ "title": "Wagon Wheel" }],
	"Paramore":	[{ "title": "Brick By Boring Brick" }, { "title": "Still Into You" }],
	"Pat Benatar":	[{ "title": "Hit Me With Your Best Shot" }, { "title": "We Belong" }],
	"Pearl Jam":	[{ "title": "Black" }],
	"Pistol Annies":	[{ "title": "I Feel A Sin Comin' On" }],
	"Plain White T's":	[{ "title": "Rhythm Of Love" }],
	"Portugal. The Man":	[{ "title": "Feel It Still" }],
	"Prince":	[{ "title": "Little Red Corvette" }],
	"Pure Prairie League":	[{ "title": "Amie" }],
	"R.E.M.":	[{ "title": "Losing My Religion" }],
	"REO Speedwagon":	[{ "title": "Take It On The Run" }],
	"Radiohead":	[{ "title": "Creep" }],
	"Reel Big Fish":	[{ "title": "She Has A Girlfriend Now" }],
	"Rod Stewart":	[{ "title": "Do You Think I'm Sexy" }, { "title": "Maggie May" }],
	"Rolling Stones":	[{ "title": "Dead Flowers" }],
	"Roxette":	[{ "title": "Listen To Your Heart" }],
	"Saigon Kick":	[{ "title": "Love Is On The Way" }],
	"Sam Palladio and Jonathan Jackson (Nashville)":	[{ "title": "Be My Girl" }],
	"Savage Garden":	[{ "title": "Truly Madly Deeply" }],
	"Saves The Day":	[{ "title": "Rocks Tonic Juice Magic" }],
	"Seal":	[{ "title": "Kiss From A Rose" }],
	"Seether":	[{ "title": "Broken" }],
	"Selena Gomez":	[{ "title": "Love You Like A Love Song" }],
	"Semisonic":	[{ "title": "Closing Time" }],
	"Shania Twain":	[{ "title": "Man I Feel Like A Woman" }, { "title": "No One Needs To Know" }, { "title": "Whose Bed Have Your Boots Been Under" }, { "title": "You're Still The One" }],
	"Shawn Mendes":	[{ "title": "I Know What You Did Last Summer" }, { "title": "Stitches" }],
	"Sheryl Crow":	[{ "title": "If It Makes You Happy" }, { "title": "Soak Up The Sun" }, { "title": "Strong Enough" }],
	"Sia":	[{ "title": "Cheap Thrills" }],
	"Simon & Garfunkel":	[{ "title": "Cecilia" }],
	"Smashing Pumpkins":	[{ "title": "1979" }],
	"Spice Girls":	[{ "title": "2 Become 1" }],
	"Starland Vocal Band":	[{ "title": "Afternoon Delight" }],
	"Stealers Wheel":	[{ "title": "Stuck In The Middle With You" }],
	"Stephen Bishop":	[{ "title": "On And On" }],
	"Steve Miller Band":	[{ "title": "The Joker" }, { "title": "The Joker - Angel Of The Morning - Angel (Mashup)" }],
	"Steve Winwood":	[{ "title": "Higher Love" }, { "title": "Valerie" }],
	"Stevie Nicks":	[{ "title": "Edge Of Seventeen" }],
	"Sting":	[{ "title": "Fields Of Gold" }],
	"Sublime":	[{ "title": "Santeria" }],
	"Sugarland":	[{ "title": "Stuck Like Glue" }],
	"Super Cassette":	[{ "title": "Be Gay, Do Drugs, Hail Satan" }],
	"TALK":	[{ "title": "Run Away To Mars" }],
	"Talking Heads":	[{ "title": "Psycho Killer" }],
	"Taylor Swift":	[{ "title": "Anti-Hero" }, { "title": "Love Story" }],
	"Tears For Fears":	[{ "title": "Everybody Wants To Rule The World" }, { "title": "Head Over Heels" }],
	"Temple Of The Dog":	[{ "title": "Hunger Strike" }],
	"Tenacious D":	[{ "title": "Fuck Her Gently" }],
	"The Angels":	[{ "title": "My Boyfriend's Back" }],
	"The Archies":	[{ "title": "Sugar Sugar" }],
	"The Beatles":	[{ "title": "8 Days A Week" }, { "title": "Across The Universe" }],
	"The Cardigans":	[{ "title": "Lovefool" }],
	"The Chainsmokers":	[{ "title": "Closer" }],
	"The Chicks":	[{ "title": "Landslide" }],
	"The Cranberries":	[{ "title": "Linger" }, { "title": "Zombie" }],
	"The Cure":	[{ "title": "In Between Days" }],
	"The Darkness":	[{ "title": "I Believe In A Thing Called Love" }],
	"The Drifters":	[{ "title": "Up On The Roof" }],
	"The Flaming Lips":	[{ "title": "Fight Test" }],
	"The Go-Go's":	[{ "title": "Our Lips Are Sealed" }],
	"The Interrupters":	[{ "title": "Gave You Everything" }],
	"The Midnight":	[{ "title": "Because The Night" }],
	"The Moody Blues":	[{ "title": "Your Wildest Dreams" }],
	"The Outfield":	[{ "title": "Your Love" }],
	"The Proclaimers":	[{ "title": "500 Miles" }],
	"The Ronettes":	[{ "title": "Be My Baby" }],
	"The Wallflowers":	[{ "title": "One Headlight" }],
	"The Weeknd":	[{ "title": "Starboy" }],
	"The Who":	[{ "title": "Behind Blue Eyes" }],
	"Thirty Seconds To Mars":	[{ "title": "The Kill" }],
	"Three Dog Night":	[{ "title": "Never Been To Spain" }],
	"Tiffany":	[{ "title": "I Think We're Alone Now" }],
	"Toad The Wet Sprocket":	[{ "title": "All I Want" }, { "title": "Fly From Heaven" }],
	"Tom Petty":	[{ "title": "Free Fallin'" }, { "title": "You Don't Know How It Feels" }],
	"Tommy Tutone":	[{ "title": "867-5309" }],
	"Tonic":	[{ "title": "If You Could Only See" }, { "title": "Mean To Me" }, { "title": "Waltz With Me" }],
	"Toto":	[{ "title": "Africa" }],
	"Tracy Chapman":	[{ "title": "Give Me One Reason" }],
	"Van Halen":	[{ "title": "Dance The Night Away" }, { "title": "Why Can't This Be Love" }],
	"Van Morrison":	[{ "title": "Brown Eyed Girl" }],
	"Vance Joy":	[{ "title": "Riptide" }],
	"Vertical Horizon":	[{ "title": "You're A God" }],
	"Weezer":	[{ "title": "Undone - The Sweater Song" }],
	"Zedd":	[{ "title": "Happy Now" }]
}

song_list.each do |artist_name, catalog_entries|
	artist = Artist.create(name: artist_name)
	artist.catalog_entries.create(catalog_entries)
end
