module.exports = [
    { "artist": "The Proclaimers", "title": "500 Miles" },
    { "artist": "Pure Prairie League", "title": "Amie" },
    { "artist": "Toad The Wet Sprocket", "title": "All I Want" },
    { "artist": "Jet", "title": "Are You Gonna Be My Girl" },
    { "artist": "Christopher Cross", "title": "Arthur's Theme (Best That You Can Do)" },
    { "artist": "Backstreet Boys", "title": "As Long As You Love Me" },
    { "artist": "Sam Palladio and Jonathan Jackson (Nashville)", "title": "Be My Girl" },
    { "artist": "Audioslave", "title": "Be Yourself" },
    { "artist": "The Who", "title": "Behind Blue Eyes" },
    { "artist": "Meredith Brooks", "title": "Bitch" },
    { "artist": "Fleetwood Mac", "title": "Bleed To Love Her" },
    { "artist": "Maren Morris", "title": "Bones" },
    { "artist": "Seether", "title": "Broken" },
    { "artist": "James Taylor", "title": "Carolina In My Mind" },
    { "artist": "Oasis", "title": "Champagne Supernova" },
    { "artist": "Sia", "title": "Cheap Thrills" },
    { "artist": "Metric", "title": "Clone" },
    { "artist": "The Chainsmokers", "title": "Closer" },
    { "artist": "Dexy's Midnight Runners", "title": "Come On Eileen" },
    { "artist": "Melissa Etheridge", "title": "Come To My Window" },
    { "artist": "Dishwalla", "title": "Counting Blue Cars" },
    { "artist": "Letters to Cleo", "title": "Cruel To Be Kind" },
    { "artist": "Huey Lewis", "title": "Cruisin'" },
    { "artist": "Michale Graves", "title": "Crying On A Saturday Night" },
    { "artist": "Jackson Browne", "title": "Doctor My Eyes" },
    { "artist": "No Doubt", "title": "Don't Speak" },
    { "artist": "Fleetwood Mac", "title": "Dreams" },
    { "artist": "Stevie Nicks", "title": "Edge Of Seventeen" },
    { "artist": "Portugal. The Man", "title": "Feel It Still" },
    { "artist": "The Flaming Lips", "title": "Fight Test" },
    { "artist": "Nitty Gritty Dirt Band", "title": "Fishin' In The Dark" },
    { "artist": "Tom Petty", "title": "Free Fallin'" },
    { "artist": "Fleetwood Mac", "title": "Go Your Own Way" },
    { "artist": "Alanis Morissette", "title": "Hand In My Pocket" },
    { "artist": "Bonnie Raitt", "title": "Have A Heart" },
    { "artist": "Creedence Clearwater Revival", "title": "Have You Ever Seen The Rain" },
    { "artist": "Alanis Morissette", "title": "Head Over Feet" },
    { "artist": "Adele", "title": "Hello" },
    { "artist": "Gin Blossoms", "title": "Hey Jealousy" },
    { "artist": "Steve Winwood", "title": "Higher Love" },
    { "artist": "Pat Benatar", "title": "Hit Me With Your Best Shot" },
    { "artist": "Marvin Gaye", "title": "I Heard It Through The Grapevine" },
    { "artist": "Shawn Mendes", "title": "I Know What You Did Last Summer" },
    { "artist": "Tiffany", "title": "I Think We're Alone Now" },
    { "artist": "Backstreet Boys", "title": "I Want It That Way" },
    { "artist": "Letters to Cleo", "title": "I Want You To Want Me" },
    { "artist": "Elton John", "title": "I'm Still Standing" },
    { "artist": "Melissa Etheridge", "title": "I'm The Only One" },
    { "artist": "Sheryl Crow", "title": "If It Makes You Happy" },
    { "artist": "The Chicks", "title": "Landslide" },
    { "artist": "The Cranberries", "title": "Linger" },
    { "artist": "Fleetwood Mac", "title": "Little Lies" },
    { "artist": "Prince", "title": "Little Red Corvette" },
    { "artist": "Creedence Clearwater Revival", "title": "Lookin' Out My Back Door" },
    { "artist": "Incubus", "title": "Love Hurts" },
    { "artist": "Justin Bieber", "title": "Love Yourself" },
    { "artist": "ABBA", "title": "Mamma Mia" },
    { "artist": "Shania Twain", "title": "Man I Feel Like A Woman" },
    { "artist": "Extreme", "title": "More Than Words" },
    { "artist": "Fleet Foxes", "title": "Mykonos" },
    { "artist": "Three Dog Night", "title": "Never Been To Spain" },
    { "artist": "The Wallflowers", "title": "One Headlight" },
    { "artist": "The Go-Go's", "title": "Our Lips Are Sealed" },
    { "artist": "Fastball", "title": "Out Of My Head" },
    { "artist": "Miley Cyrus", "title": "Party In The U.S.A." },
    { "artist": "Bastille", "title": "Pompeii" },
    { "artist": "Talking Heads", "title": "Psycho Killer" },
    { "artist": "Backstreet Boys", "title": "Quit Playing Games With My Heart" },
    { "artist": "Led Zeppelin", "title": "Rock And Roll" },
    { "artist": "Lorde", "title": "Royals" },
    { "artist": "Nathaniel Rateliff", "title": "S.O.B." },
    { "artist": "Miley Cyrus", "title": "See You Again" },
    { "artist": "Ariana Grande", "title": "Side To Side" },
    { "artist": "Bonnie Raitt", "title": "Something To Talk About" },
    { "artist": "Dusty Springfield", "title": "Son Of A Preacher Man" },
    { "artist": "The Weeknd", "title": "Starboy" },
    { "artist": "Deana Carter", "title": "Strawberry Wine" },
    { "artist": "Neil Diamond", "title": "Sweet Caroline" },
    { "artist": "REO Speedwagon", "title": "Take It On The Run" },
    { "artist": "John Denver", "title": "Take Me Home, Country Roads" },
    { "artist": "NSYNC", "title": "Tearing Up My Heart" },
    { "artist": "Lady Gaga", "title": "Telephone" },
    { "artist": "Del McCoury Band", "title": "That Ol' Train" },
    { "artist": "Fastball", "title": "The Way" },
    { "artist": "Natalie Imbruglia", "title": "Torn" },
    { "artist": "Steve Winwood", "title": "Valerie" },
    { "artist": "4 Non Blondes", "title": "What's Up" },
    { "artist": "Alison Krauss", "title": "When You Say Nothing At All" },
    { "artist": "Shania Twain", "title": "Whose Bed Have Your Boots Been Under" },
    { "artist": "Van Halen", "title": "Why Can't This Be Love" },
    { "artist": "Oasis", "title": "Wonderwall" },
    { "artist": "Jimmy Eat World", "title": "Work" },
    { "artist": "Tom Petty", "title": "You Don't Know How It Feels" },
    { "artist": "Alanis Morissette", "title": "You Learn" },
    { "artist": "Smashing Pumpkins", "title": "1979" },
    { "artist": "Spice Girls", "title": "2 Become 1" },
    { "artist": "The Beatles", "title": "8 Days A Week" },
    { "artist": "Tommy Tutone", "title": "867-5309" },
    { "artist": "Dolly Parton", "title": "9 To 5" },
    { "artist": "Toto", "title": "Africa" },
    { "artist": "Starland Vocal Band", "title": "Afternoon Delight" },
    { "artist": "Juice Newton", "title": "Angel Of The Morning" },
    { "artist": "Taylor Swift", "title": "Anti-Hero" },
    { "artist": "Eddie Money", "title": "Baby Hold On" },
    { "artist": "Creedence Clearwater Revival", "title": "Bad Moon Rising" },
    { "artist": "Alannah Myles", "title": "Black Velvet" },
    { "artist": "Brooks & Dunn", "title": "Boot Scootin' Boogie" },
    { "artist": "Don Henley", "title": "Boys Of Summer" },
    { "artist": "Deep Blue Something", "title": "Breakfast At Tiffany's" },
    { "artist": "Echosmith", "title": "Bright" },
    { "artist": "Van Morrison", "title": "Brown Eyed Girl" },
    { "artist": "Barenaked Ladies", "title": "Call And Answer" },
    { "artist": "Semisonic", "title": "Closing Time" },
    { "artist": "David Shaffer", "title": "Cloud" },
    { "artist": "Avril Lavigne", "title": "Complicated" },
    { "artist": "Radiohead", "title": "Creep" },
    { "artist": "Elton John", "title": "Crocodile Rock" },
    { "artist": "Billy Idol", "title": "Dancing With Myself" },
    { "artist": "Rolling Stones", "title": "Dead Flowers" },
    { "artist": "Eagles", "title": "Desperado" },
    { "artist": "Rod Stewart", "title": "Do You Think I'm Sexy" },
    { "artist": "Beach Boys", "title": "Don't Worry Baby" },
    { "artist": "Incubus", "title": "Drive" },
    { "artist": "Ingrid Michaelson", "title": "Everybody" },
    { "artist": "Elle King", "title": "Exes And Ohs" },
    { "artist": "George Michael", "title": "Faith" },
    { "artist": "Sting", "title": "Fields Of Gold" },
    { "artist": "Johnny Cash", "title": "Folsom Prison Blues" },
    { "artist": "Garth Brooks", "title": "Friends In Low Places" },
    { "artist": "Tenacious D", "title": "Fuck Her Gently" },
    { "artist": "CHVRCHES", "title": "Get Out" },
    { "artist": "Little Big Town", "title": "Girl Crush" },
    { "artist": "Tracy Chapman", "title": "Give Me One Reason" },
    { "artist": "Lindsey Buckingham", "title": "Holiday Road" },
    { "artist": "Blue Swede", "title": "Hooked On A Feeling" },
    { "artist": "Eagles", "title": "Hotel California" },
    { "artist": "The Darkness", "title": "I Believe In A Thing Called Love" },
    { "artist": "Pistol Annies", "title": "I Feel A Sin Comin' On" },
    { "artist": "Lee Ann Womack", "title": "I Hope You Dance" },
    { "artist": "Edwin McCain", "title": "I'll Be" },
    { "artist": "Cher", "title": "If I Could Turn Back Time" },
    { "artist": "Tonic", "title": "If You Could Only See" },
    { "artist": "The Cure", "title": "In Between Days" },
    { "artist": "John Prine", "title": "In Spite Of Ourselves" },
    { "artist": "Go West", "title": "King Of Wishful Thinking" },
    { "artist": "Nat King Cole", "title": "L-O-V-E" },
    { "artist": "Roxette", "title": "Listen To Your Heart" },
    { "artist": "Saigon Kick", "title": "Love Is On The Way" },
    { "artist": "Taylor Swift", "title": "Love Story" },
    { "artist": "Selena Gomez", "title": "Love You Like A Love Song" },
    { "artist": "The Cardigans", "title": "Lovefool" },
    { "artist": "Rod Stewart", "title": "Maggie May" },
    { "artist": "The Angels", "title": "My Boyfriend's Back" },
    { "artist": "Brooks & Dunn", "title": "Neon Moon" },
    { "artist": "Ben Folds", "title": "Not The Same" },
    { "artist": "Lil Nas X", "title": "Old Town Road" },
    { "artist": "Madonna", "title": "Papa Don't Preach" },
    { "artist": "Creedence Clearwater Revival", "title": "Proud Mary" },
    { "artist": "Plain White T's", "title": "Rhythm Of Love" },
    { "artist": "Vance Joy", "title": "Riptide" },
    { "artist": "Saves The Day", "title": "Rocks Tonic Juice Magic" },
    { "artist": "Nat King Cole", "title": "Route 66" },
    { "artist": "Blues Traveler", "title": "Run Around" },
    { "artist": "TALK", "title": "Run Away To Mars" },
    { "artist": "Sublime", "title": "Santeria" },
    { "artist": "Journey", "title": "Separate Ways" },
    { "artist": "Backstreet Boys", "title": "Show Me The Meaning Of Being Lonely" },
    { "artist": "America", "title": "Sister Golden Hair" },
    { "artist": "Israel Kamakawiwo'ole", "title": "Somewhere Over The Rainbow" },
    { "artist": "David Shaffer", "title": "Soon My Love" },
    { "artist": "No Doubt", "title": "Spiderwebs" },
    { "artist": "Fountains Of Wayne", "title": "Stacy's Mom" },
    { "artist": "Jonathan Coulton", "title": "Still Alive" },
    { "artist": "Bob Marley", "title": "Stir It Up" },
    { "artist": "Shawn Mendes", "title": "Stitches" },
    { "artist": "Sheryl Crow", "title": "Strong Enough" },
    { "artist": "Sugarland", "title": "Stuck Like Glue" },
    { "artist": "The Archies", "title": "Sugar Sugar" },
    { "artist": "Bryan Adams", "title": "Summer Of 69" },
    { "artist": "James Taylor", "title": "Sweet Baby James" },
    { "artist": "Eagles", "title": "Take It Easy" },
    { "artist": "Eddie Money", "title": "Take Me Home Tonight" },
    { "artist": "A-Ha", "title": "Take On Me" },
    { "artist": "Chris Stapleton", "title": "Tennessee Whiskey" },
    { "artist": "Steve Miller Band", "title": "The Joker" },
    { "artist": "Ingrid Michaelson", "title": "The Way I Am" },
    { "artist": "Frank Sinatra", "title": "The Way You Look Tonight" },
    { "artist": "Gin Blossoms", "title": "Til I Hear It From You" },
    { "artist": "Mr. Big", "title": "To Be With You" },
    { "artist": "The Drifters", "title": "Up On The Roof" },
    { "artist": "Old Crow Medicine Show", "title": "Wagon Wheel" },
    { "artist": "Katrina and the Waves", "title": "Walking On Sunshine" },
    { "artist": "Jason Derulo", "title": "Want To Want Me" },
    { "artist": "Barenaked Ladies", "title": "What A Good Boy" },
    { "artist": "Eric Clapton", "title": "Wonderful Tonight" },
    { "artist": "Miley Cyrus", "title": "Wrecking Ball" },
    { "artist": "Alanis Morissette", "title": "You Oughta Know" },
    { "artist": "Shania Twain", "title": "You're Still The One" },
    { "artist": "Chicago", "title": "You're The Inspiration" },
    { "artist": "The Outfield", "title": "Your Love" },
    { "artist": "The Moody Blues", "title": "Your Wildest Dreams" },
    { "artist": "The Cranberries", "title": "Zombie" },
    { "artist": "Tears For Fears", "title": "Everybody Wants To Rule The World" },
    { "artist": "Tears For Fears", "title": "Head Over Heels" },
    { "artist": "Stephen Bishop", "title": "On And On" },
    { "artist": "Stealers Wheel", "title": "Stuck In The Middle With You" },
    { "artist": "Gin Blossoms", "title": "29" },
    { "artist": "Van Halen", "title": "Dance The Night Away" },
    { "artist": "Bruno Mars", "title": "Locked Out Of Heaven" },
    { "artist": "Zedd", "title": "Happy Now" },
]
